### ISSUE TITLE
Provide a different experience around Term Entry vs Term Search

### ISSUE THREAD

**Issue by djbrooke** [gdcc/dataverse-external-vocab-support#1]
In a recent demo of external vocab there was text populated in the advanced search page. This is good and we want this, as it greatly increases the usefulness of this feature. 

One small change request - there was some text added on the advanced search page - for example, "Add a Term" was shown in at least one of the boxes. This is different than other search boxes which have no text. @qqmyers mentioned that a possible solution would be to make a change to handle the different context (entry vs search) so that the same text is not pre-populated in both scenarios.

**Comment by qqmyers** [comment]
from advanced search: 
![image](https://user-images.githubusercontent.com/6731983/133316197-89e9b1aa-92d7-4e67-b8ab-869c14f15716.png)

**Comment by qqmyers** [comment]
Addressed in Dataverse.
