### ISSUE TITLE
Error in example causes failure in Dataverse DatasetFieldServiceBean validation of inputs

### ISSUE THREAD

**Issue by qqmyers** [gdcc/dataverse-external-vocab-support#10]
https://github.com/gdcc/dataverse-external-vocab-support/blob/95d92f397d101d692af33fb1383529351f051d4c/examples/config/affiliation.json#L10
should be "vocabs":{},
so that vocabs is a json object rather than a string. 
FWIW: There is a [schema](https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/config/CVocConf.schema.json) (hopefully up to date) that could be used to validate this.

**Comment by pdurbin** [comment]
If examples/config/affiliation.json is the only example, I think this PR fixed it:

- #11

Closing. Please feel free to re-open if there are others! Or if more tooling or docs are desired for schema validation.
