### ISSUE TITLE
Compressed view on dataset creation

### ISSUE THREAD

**Issue by djbrooke** [gdcc/dataverse-external-vocab-support#2]
In a recent demo of external vocabulary, on the page for creating a dataset, there was a vertically compressed view for adding a term. @qqmyers mentioned that this may be because the JS did not know the size of the box when the page was loaded.

**Comment by qqmyers** [comment]
On the create page:
![image](https://user-images.githubusercontent.com/6731983/133316026-b53534d8-e652-4ec4-ba78-19d04eb80903.png)

**Comment by qqmyers** [comment]
This was fixed with changes in Dataverse.
