### ISSUE TITLE
The LocalContexts script shouldn't hardcode the server URL

### ISSUE THREAD

**Issue by qqmyers** [gdcc/dataverse-external-vocab-support#24]
The https://github.com/gdcc/dataverse-external-vocab-support/blob/3bf4b0e6298e4937f3f8efd066805a15b479c352/packages/local_contexts/lc-cvoc-conf.json#L7 and a new[ cvoc-url entry ](https://github.com/gdcc/dataverse-external-vocab-support/blob/3bf4b0e6298e4937f3f8efd066805a15b479c352/examples/config/CVocConf.schema.json#L215) should be used instead of hardcoding the https://github.com/gdcc/dataverse-external-vocab-support/blob/3bf4b0e6298e4937f3f8efd066805a15b479c352/packages/local_contexts/local_contexts.js#L4 and https://github.com/gdcc/dataverse-external-vocab-support/blob/3bf4b0e6298e4937f3f8efd066805a15b479c352/packages/local_contexts/local_contexts.js#L53 in the javascript.
This would allow people to switch to use the https://sandbox.localcontextshub.org site instead for testing.

I think https://github.com/gdcc/dataverse-external-vocab-support/blob/3bf4b0e6298e4937f3f8efd066805a15b479c352/packages/local_contexts/lc-cvoc-conf.json#L9  is incorrect since we are storing the whole URL for the project - it should be empty(undefined?) instead, @transfluxus  - this may be why the API has trouble - not sure.

**Comment by transfluxus** [comment]
@qqmyers 
**allowing it to be changed easily to the LC Sanbbox:**

How would I access the cvoc config from out of the js script?

**being able to use the API to set the value:**
I could track it down to this function, which validates the value:
https://github.com/IQSS/dataverse/blob/2792cf968348d4cdf49b5499bbb68ae93eaae40c/src/main/java/edu/harvard/iq/dataverse/DatasetFieldServiceBean.java#L783

and indeed, adding:
```
    "vocabs": {
      "localcontexts": {
        "uriSpace": "https://localcontextshub.org"
      }
    }
```
fixed it
