### ISSUE TITLE
Funder registry URI does not transform to Funder Name 

### ISSUE THREAD

**Issue by gwendoux** [gdcc/dataverse-external-vocab-support#27]
When using the Funder Registry controlled vocabulary with the scripts/fundreg‧js script, the user can search for and select a funder agency by name. The form is saved successfully. 

However, upon returning to the metadata tab, only the URI of the selected funder agency is displayed, rather than its name. This behavior differs from the expected functionality where the funder agency name is correctly displayed.

![funder](https://github.com/user-attachments/assets/8b510b01-25f5-49b3-b8f9-8b6733bb4101)

Expected:
![funder_OK](https://github.com/user-attachments/assets/a476ee08-0078-468c-aaa1-1418a983a166)

**Comment by qqmyers** [comment]
Hmm - I'm guessing either they changed their URLs or some organizations use different forms. The script as it is now assumes that FundReg identifiers start with https://github.com/gdcc/dataverse-external-vocab-support/blob/5c341a0c2ec727c9c65026faaab7eff5ea221bd9/scripts/fundreg.js#L24
which your example does not. Changing that line (allow both or updating to https://doi.org/10.13039 if that's used all the time now) should fix it.

Please note though that I think CrossRef's FundReg service is going away and it is now recommended that ROR be used instead.

**Comment by gwendoux** [comment]
@qqmyers I've been working on a fix for this issue, but I haven't asked for a pull request yet.

Do you think it's worth submitting?

Maybe it could be interesting for others to add a note somewhere (maybe in the JavaScript?) suggesting using ROR instead of Crossref's Fundref.

**Comment by qqmyers** [comment]
Both sound fine - it would be nice to have the fix in case any one is using it now and having a note to consider ROR instead sounds helpful as well.
