### ISSUE TITLE
Dropdown vs Typeahead for two terms

### ISSUE THREAD

**Issue by djbrooke** [gdcc/dataverse-external-vocab-support#3]
UNESCO and Agrovoc were presented as selections in a type-ahead. We'd want to use a dropdown to handle these two selections instead.

**Comment by qqmyers** [comment]
They can be both. It looks like there's some confusion when using the 'bootstrap' theme for the select2 widget. If I switch to 'classic'  (and remove a css rule from DV), it looks like
![image](https://user-images.githubusercontent.com/6731983/133298247-aefbbcba-c182-4819-a10c-2c18ce9ad388.png)

**Comment by TaniaSchlatter** [comment]
It looks like @qqmyers's solution above would address the issue. The intention behind this issue is less about changing functionality and more about making the functionality clear to the user.
